FROM ubuntu:focal

ENV LANG=fr_FR.UTF-8

RUN echo "LANG=\"$LANG\"\nLANGUAGE=\"fr_FR:fr\"\nLC_NUMERIC=\"$LANG\"\nLC_TIME=\"$LANG\"\nLC_MONETARY=\"$LANG\"\nLC_PAPER=\"$LANG\"\nLC_IDENTIFICATION=\"$LANG\"\nLC_NAME=\"$LANG\"\nLC_ADDRESS=\"$LANG\"\nLC_TELEPHONE=\"$LANG\"\nLC_MEASUREMENT=\"$LANG\"" >>/etc/default/locale


RUN apt-get update && \
    apt-get -y install cron bzip2 tar language-pack-fr vim

RUN echo "0 2 * * * root bash /home/backups/BACKUP.sh >>/var/log/backup.log" >>/etc/cron.d/backups;

WORKDIR /home/backups

CMD service cron start; \
    sleep infinity;
