FROM node:8.11.1

WORKDIR /home/front

CMD if [ "$NODE_ENV" = "production" ] || [ "$NODE_ENV" = "qa" ]; then \
        npm install && \
        npm run build && \
        cp -RT build dist && \
        tail -f /dev/null; \
    else \
        npm install && \
        npm start; \
    fi
