export const FETCH_DECLARATIONS_LOADING = 'FETCH_DECLARATIONS_LOADING'
export const FETCH_DECLARATIONS_SUCCESS = 'FETCH_DECLARATIONS_SUCCESS'
export const FETCH_DECLARATIONS_FAILURE = 'FETCH_DECLARATIONS_FAILURE'
export const HIDE_EMPLOYER_FILE_PREVIEW = 'HIDE_EMPLOYER_FILE_PREVIEW'
export const SHOW_EMPLOYER_FILE_PREVIEW = 'SHOW_EMPLOYER_FILE_PREVIEW'
export const HIDE_INFO_FILE_PREVIEW = 'HIDE_DOC_INFO_FILE_PREVIEW'
export const SHOW_INFO_FILE_PREVIEW = 'SHOW_DOC_INFO_FILE_PREVIEW'
export const FETCH_EMPLOYER_SUCCESS = 'FETCH_EMPLOYER_SUCCESS'
export const POST_EMPLOYER_DOC_FAILURE = 'POST_EMPLOYER_DOC_FAILURE'
export const POST_EMPLOYER_DOC_LOADING = 'POST_EMPLOYER_DOC_LOADING'
export const FETCH_DECLARATION_SUCCESS = 'FETCH_DECLARATION_SUCCESS'
export const POST_DECLARATION_INFO_FAILURE = 'POST_DECLARATION_INFO_FAILURE'
export const POST_DECLARATION_INFO_LOADING = 'POST_DECLARATION_INFO_LOADING'
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const FETCH_STATUS_LOADING = 'FETCH_STATUS_LOADING'
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS'
export const FETCH_STATUS_FAILURE = 'FETCH_STATUS_FAILURE'
export const FETCH_ACTIVE_MONTH_LOADING = 'FETCH_ACTIVE_MONTH_LOADING'
export const FETCH_ACTIVE_MONTH_SUCCESS = 'FETCH_ACTIVE_MONTH_SUCCESS'
export const FETCH_ACTIVE_MONTH_FAILURE = 'FETCH_ACTIVE_MONTH_FAILURE'
export const FETCH_ACTIVE_DECLARATION_LOADING =
  'FETCH_ACTIVE_DECLARATION_LOADING'
export const FETCH_ACTIVE_DECLARATION_SUCCESS =
  'FETCH_ACTIVE_DECLARATION_SUCCESS'
export const FETCH_ACTIVE_DECLARATION_FAILURE =
  'FETCH_ACTIVE_DECLARATION_FAILURE'
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT'
export const SHOW_DECLARATION_TRANSMITTED_DIALOG =
  'SHOW_DECLARATION_TRANSMITTED_DIALOG'
export const HIDE_DECLARATION_TRANSMITTED_DIALOG =
  'HIDE_DECLARATION_TRANSMITTED_DIALOG'

export const FETCH_ACTIVE_DECLARATION_MONTHS_LOADING =
  'FETCH_ACTIVE_DECLARATION_MONTHS_LOADING'
export const FETCH_ACTIVE_DECLARATION_MONTHS_SUCCESS =
  'FETCH_ACTIVE_DECLARATION_MONTHS_SUCCESS'
export const FETCH_ACTIVE_DECLARATION_MONTHS_FAILURE =
  'FETCH_ACTIVE_DECLARATION_MONTHS_FAILURE'
